# Generated by Django 5.0.4 on 2024-04-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=(1, '1')),
        ),
    ]
